#!/usr/bin/env bash

set -euxo pipefail

mk() { mkdir -p "${1}" && chmod 777 "${1}"; }

mk '/var/tmp/pip'

if [ "${1}" = 'start' ]; then
	mkdir -p "${HOME}/.cache"
	ln -s '/var/tmp/pip' "${HOME}/.cache/pip"
fi

if [ "${1}" = 'stop' ]; then
	rm -f "${HOME}/.cache/pip"
fi
