#!/usr/bin/env bash

set -euxo pipefail

cd /var/cache/elan
if [ -f "${1}.tar" ]; then
	tar -xf "${1}.tar" -C ~
else
	elan toolchain install "${1}"
	tar -cf "${1}.tar" -C ~ ".elan/toolchains/leanprover--lean4---${1}"
fi
